export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"项目主页"},["/README.md"]],
  ["v-52044e16","/src/adapter/disable.html",{"title":"布局与功能禁用"},[":md"]],
  ["v-c4f020d0","/src/adapter/encrypt.html",{"title":"密码加密的文章"},[":md"]],
  ["v-a0b3952a","/src/adapter/layout.html",{"title":"布局"},[":md"]],
  ["v-3649d426","/src/adapter/page.html",{"title":"页面配置"},[":md"]],
  ["v-3b7470b6","/src/adapter/QQBot.html",{"title":"QQBot适配器"},[":md"]],
  ["v-49851004","/src/adapter/",{"title":"适配器使用指南"},["/src/adapter/README.md"]],
  ["v-7517aed9","/src/demo/disable.html",{"title":"布局与功能禁用"},[":md"]],
  ["v-3ba1c57c","/src/demo/encrypt.html",{"title":"密码加密的文章"},[":md"]],
  ["v-546fd9f2","/src/demo/layout.html",{"title":"布局"},[":md"]],
  ["v-697c033c","/src/demo/markdown.html",{"title":"Markdown 展示"},[":md"]],
  ["v-71832e7c","/src/demo/page.html",{"title":"页面配置"},[":md"]],
  ["v-b334c830","/src/demo/",{"title":"主要功能与配置演示"},["/src/demo/README.md"]],
  ["v-2c4beef7","/src/guide/",{"title":"指南"},["/src/guide/README.md"]],
  ["v-04881c91","/src/guide/bar/baz.html",{"title":"Baz"},[":md"]],
  ["v-366ba1f3","/src/guide/bar/",{"title":"Bar 功能"},["/src/guide/bar/README.md"]],
  ["v-315bcae2","/src/guide/foo/ray.html",{"title":"Ray"},[":md"]],
  ["v-366da7a0","/src/guide/foo/",{"title":"Foo 功能"},["/src/guide/foo/README.md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
